name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 1 * * *"
    - cron: "0 3 * * *"
    - cron: "0 6 * * *"
    - cron: "0 9 * * *"
    - cron: "0 12 * * *"
    - cron: "0 15 * * *"
    - cron: "0 18 * * *"
    - cron: "0 21 * * *"
    - cron: "0 23 * * *"
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: public build
        run: |
          npm ci
          node ./app.js
          npm run build --if-present
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
